### ISSUE TITLE
DIF purification

### ISSUE THREAD

**Issue by patriciamar** [patriciamar/ShinyItemAnalysis#179]
Adding purification to DIF methods will be great!

**Comment by drabinova** [comment]
So far added in MH, Lord, Raju and LR but only with total score. When standardized total score is used in difLogistic() difR function, there is error. This is because difLogistic function does not know how to compute matching variable without DIF items. In difNLR it is not implemented, so there is no purification in NLR and DDF.

**Comment by drabinova** [comment]
Po kontrole prosim uzavrit
